# https://github.com/kubedb/docs/raw/v2020.12.10/docs/examples/mysql/quickstart/demo-1.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myadmin
  name: myadmin
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myadmin
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        imagePullPolicy: Always
        name: phpmyadmin
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: PMA_ARBITRARY
            value: '1'

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myadmin
  name: myadmin
  namespace: demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: myadmin
  type: LoadBalancer
