# https://github.com/kubedb/cli/blob/0.12.0/docs/examples/mysql/quickstart/demo-2.yaml
---
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-quickstart
  namespace: demo
spec:
  version: "8.0-v2"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  #terminationPolicy: DoNotTerminate
  terminationPolicy: Delete
