# https://github.com/kubedb/docs/blob/master/docs/examples/mysql/clustering/demo-1.yaml
---
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-clustering
  namespace: demo
spec:
  version: "5.7.25"
  replicas: 3
  topology:
    mode: GroupReplication
    group:
      name: "dc002fc3-c412-4d18-b1d4-66c1fbfbbc9b"
      baseServerID: 100
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut

